// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SortSchedule.Infrastructure.Persistence;

#nullable disable

namespace SortSchedule.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502143156_AddUserCreatePermission")]
    partial class AddUserCreatePermission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SortSchedule.Domain.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AppRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a8ebea7-0d17-4178-ad20-9ea0f0c2f771"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("4f7d6a97-b228-4a62-a308-91530c223a84"),
                            Name = "Lecturer"
                        },
                        new
                        {
                            Id = new Guid("2f5b4f8e-7659-4955-bad6-b526639c3cdb"),
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("SortSchedule.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("SortSchedule.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Resource", "Action")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1a562b1-4a59-42e1-9d67-33c87332c19e"),
                            Action = 0,
                            Name = "Read Schedule",
                            Resource = "Schedule"
                        },
                        new
                        {
                            Id = new Guid("92a3a69a-40d9-4db8-8f2b-df9d23ed1d27"),
                            Action = 5,
                            Name = "Manage Schedule",
                            Resource = "Schedule"
                        },
                        new
                        {
                            Id = new Guid("61a5c1f0-8041-456a-8e4e-3bc38a2b0e76"),
                            Action = 2,
                            Name = "Update Schedule",
                            Resource = "Schedule"
                        },
                        new
                        {
                            Id = new Guid("f8e1c2e6-b94f-4c82-936a-b6a78d54a43d"),
                            Action = 1,
                            Name = "Create Free Time",
                            Resource = "FreeTime"
                        },
                        new
                        {
                            Id = new Guid("a2e7f3d0-4b19-4a92-9c21-6a2b3c4d5e6f"),
                            Action = 1,
                            Name = "Create Feedback",
                            Resource = "Feedback"
                        },
                        new
                        {
                            Id = new Guid("c4b72a1f-3d8e-45a1-9f2c-6d3e4f5a1b2c"),
                            Action = 0,
                            Name = "Read Feedback",
                            Resource = "Feedback"
                        },
                        new
                        {
                            Id = new Guid("e5c83b20-4e9f-46b2-a03d-7e4f5a6b2c3d"),
                            Action = 2,
                            Name = "Update Feedback",
                            Resource = "Feedback"
                        },
                        new
                        {
                            Id = new Guid("d1c83b20-4e9f-46b2-a03d-7e4f5a6b2d1c"),
                            Action = 1,
                            Name = "Create User",
                            Resource = "User"
                        });
                });

            modelBuilder.Entity("SortSchedule.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SortSchedule.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Effect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("2f5b4f8e-7659-4955-bad6-b526639c3cdb"),
                            PermissionId = new Guid("d1a562b1-4a59-42e1-9d67-33c87332c19e"),
                            Effect = 0
                        },
                        new
                        {
                            RoleId = new Guid("4f7d6a97-b228-4a62-a308-91530c223a84"),
                            PermissionId = new Guid("d1a562b1-4a59-42e1-9d67-33c87332c19e"),
                            Effect = 0
                        },
                        new
                        {
                            RoleId = new Guid("4f7d6a97-b228-4a62-a308-91530c223a84"),
                            PermissionId = new Guid("f8e1c2e6-b94f-4c82-936a-b6a78d54a43d"),
                            Effect = 0
                        },
                        new
                        {
                            RoleId = new Guid("4f7d6a97-b228-4a62-a308-91530c223a84"),
                            PermissionId = new Guid("a2e7f3d0-4b19-4a92-9c21-6a2b3c4d5e6f"),
                            Effect = 0
                        },
                        new
                        {
                            RoleId = new Guid("6a8ebea7-0d17-4178-ad20-9ea0f0c2f771"),
                            PermissionId = new Guid("92a3a69a-40d9-4db8-8f2b-df9d23ed1d27"),
                            Effect = 0
                        },
                        new
                        {
                            RoleId = new Guid("6a8ebea7-0d17-4178-ad20-9ea0f0c2f771"),
                            PermissionId = new Guid("61a5c1f0-8041-456a-8e4e-3bc38a2b0e76"),
                            Effect = 0
                        },
                        new
                        {
                            RoleId = new Guid("6a8ebea7-0d17-4178-ad20-9ea0f0c2f771"),
                            PermissionId = new Guid("d1a562b1-4a59-42e1-9d67-33c87332c19e"),
                            Effect = 0
                        },
                        new
                        {
                            RoleId = new Guid("6a8ebea7-0d17-4178-ad20-9ea0f0c2f771"),
                            PermissionId = new Guid("c4b72a1f-3d8e-45a1-9f2c-6d3e4f5a1b2c"),
                            Effect = 0
                        },
                        new
                        {
                            RoleId = new Guid("6a8ebea7-0d17-4178-ad20-9ea0f0c2f771"),
                            PermissionId = new Guid("e5c83b20-4e9f-46b2-a03d-7e4f5a6b2c3d"),
                            Effect = 0
                        },
                        new
                        {
                            RoleId = new Guid("6a8ebea7-0d17-4178-ad20-9ea0f0c2f771"),
                            PermissionId = new Guid("d1c83b20-4e9f-46b2-a03d-7e4f5a6b2d1c"),
                            Effect = 0
                        });
                });

            modelBuilder.Entity("SortSchedule.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("SortSchedule.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SortSchedule.Domain.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SortSchedule.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("SortSchedule.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SortSchedule.Domain.Entities.AppRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SortSchedule.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("SortSchedule.Domain.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SortSchedule.Domain.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SortSchedule.Domain.Entities.AppRole", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SortSchedule.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
